// vue-app/src/shared/components/contact/contact.vue
<template>
    <div class="container">
                    <div class="flex-container">
                        <h1>
                            Contact Us
                        </h1>
                            <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                Architecto perferendis amet rerum consectetur illo minima dignissimos, 
                                maiores sed fugiat magni porro quae, quis impedit, aliquam labore nemo. 
                                Perferendis numquam non earum expedita, voluptas? Incidunt saepe alias quo minus sit perspiciatis animi. 
                                Eligendi unde dignissimos amet natus sint veritatis autem deleniti architecto dolorum ut explicabo 
                                minima ad necessitatibus sed accusantium voluptas libero delectus, pariatur laudantium neque 
                                nulla impedit est animi? Quod, pariatur reprehenderit quasi sint suscipit iste eius cum qui 
                                dolorum perspiciatis, placeat assumenda, deleniti. Minima ipsam possimus fugit animi excepturi 
                                ullam magni debitis dolorem maiores nemo repellat culpa minus placeat officia temporibus quod 
                                odio cum laborum, distinctio in sunt architecto, ex ratione. Minima autem distinctio deserunt 
                                temporibus doloremque dolorum quisquam eaque doloribus asperiores illo suscipit expedita atque 
                                cumque sunt soluta fugit, vitae at libero neque architecto facere quidem sed. Accusantium temporibus, 
                                molestiae id perferendis labore harum qui asperiores, fugit vitae aliquid corrupti distinctio aperiam 
                                laboriosam atque doloremque quam ipsam illum impedit. Temporibus eaque amet ut non autem pariatur 
                                laudantium ex debitis laborum fuga animi, doloremque maiores esse ipsum maxime modi, beatae perferendis, 
                                exercitationem nostrum mollitia neque inventore recusandae? Reprehenderit temporibus est at laudantium 
                                odio animi odit, deserunt non repellat maiores! 
                            </p>
                    </div>
                </div>                
</template>

<script>
export default {
  name: "Contact"
}
</script>

<style scoped>
.flex-container {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  align-self: center;
  text-align:center;
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
  text-align: center;
}
</style>

// react-app/src/shared/components/contact.js
import React, { Component } from 'react'
import './contact.css';

class Contact extends Component {
    render() {
        return (
 <div>
                <div className="container">
                    <div className="flex-container">
                        <h1>
                            Contact Us
                        </h1>
                            <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                Architecto perferendis amet rerum consectetur illo minima dignissimos, 
                                maiores sed fugiat magni porro quae, quis impedit, aliquam labore nemo. 
                                Perferendis numquam non earum expedita, voluptas? Incidunt saepe alias quo minus sit perspiciatis animi. 
                                Eligendi unde dignissimos amet natus sint veritatis autem deleniti architecto dolorum ut explicabo 
                                minima ad necessitatibus sed accusantium voluptas libero delectus, pariatur laudantium neque 
                                nulla impedit est animi? Quod, pariatur reprehenderit quasi sint suscipit iste eius cum qui 
                                dolorum perspiciatis, placeat assumenda, deleniti. Minima ipsam possimus fugit animi excepturi 
                                ullam magni debitis dolorem maiores nemo repellat culpa minus placeat officia temporibus quod 
                                odio cum laborum, distinctio in sunt architecto, ex ratione. Minima autem distinctio deserunt 
                                temporibus doloremque dolorum quisquam eaque doloribus asperiores illo suscipit expedita atque 
                                cumque sunt soluta fugit, vitae at libero neque architecto facere quidem sed. Accusantium temporibus, 
                                molestiae id perferendis labore harum qui asperiores, fugit vitae aliquid corrupti distinctio aperiam 
                                laboriosam atque doloremque quam ipsam illum impedit. Temporibus eaque amet ut non autem pariatur 
                                laudantium ex debitis laborum fuga animi, doloremque maiores esse ipsum maxime modi, beatae perferendis, 
                                exercitationem nostrum mollitia neque inventore recusandae? Reprehenderit temporibus est at laudantium 
                                odio animi odit, deserunt non repellat maiores! 
                            </p>
                    </div>
                </div>                
            </div>
        )
    }
}
export default Contact;
