// react-app/src/cart/cart.js
import React, { Component } from 'react';
import './cart.css';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { fetchCarts, addCartCount, reduceCartCount } from '../shared/actions/movieActions';

let subTotal=0;
let taxable =0;
let grandTotal =0;
function total(cart){
    subTotal = 0;
    taxable = 0;
    grandTotal = 0;
    for(let i=0; i<cart.length; i++){  
        subTotal += cart[i].UnitPrice * cart[i].Quantity;
    } 
    taxable = subTotal/10;
    grandTotal = subTotal+taxable;
}
class Cart extends Component {
    constructor(props) {
        super(props);  
        this.addCartCount = this.addCartCount.bind(this);
        this.reduceCartCount = this.reduceCartCount.bind(this);
    }
    componentWillMount() {
        this.props.fetchCarts();
    }
    addCartCount(id) {  
        this.props.addCartCount(id);
    }
    reduceCartCount(id){
        this.props.reduceCartCount(id);
    }
    render() {
    const CartItems = this.props.cart.map(movie => (
        <tr key={movie.ProductId}>
            <td><strong>{movie.Title}</strong></td>
            <td> 
                <button className="button1" 
                onClick={() => 
                this.addCartCount(movie.ProductId)}>
                +
                </button>
                &nbsp; &nbsp;
                {movie.Quantity}
                &nbsp; &nbsp;
                <button className="button1"
                    onClick={() =>
                        this.reduceCartCount(movie.ProductId)}>
                    -
                </button>
            </td>
            <td>$ {movie.UnitPrice}</td>
            <td>$ {(movie.UnitPrice * movie.Quantity).toFixed(2)}</td>
        </tr>
    ));
        total(this.props.cart)
        return (
            <div>
                <div className="container">
                    <table>
                        <tbody>
                        <tr>
                            <th>| Item(s)    |</th>
                            <th>| Quantity   |</th>
                            <th>| Unit Price |</th>
                            <th>| Total Prices     |</th>
                        </tr>
                       {CartItems}
        <tr>    
            <td colSpan="2"></td>
            <td>
                 <strong>
                     SubTotal : 
                 </strong>
            </td>
                <td>
                  <strong>
                       $ {subTotal.toFixed(2)} 
                  </strong>
                </td>
        </tr>
        <tr>    
            <td colSpan="2"></td>
            <td>
                <strong>
                    Tax Applicable :
                </strong>
            </td>
            <td>
                <strong>
                    $ {taxable.toFixed(2)}
                </strong>
            </td>
        </tr>
        <tr>    
            <td colSpan="2"></td>
            <td>
                <strong>
                    Total Billable Amount : 
                </strong>
            </td>
            <td>
                <strong>
                    $ {grandTotal.toFixed(2)}
                </strong>
            </td>
        </tr>
        <tr>
            <td colSpan="2">
                <button className="cart-button">
                    checkout!<span className="glyphicon glyphicon-shopping-cart"></span>    
                </button>
            </td>
            <td colSpan="2">
                <button className="cart-button">
                     Go Back
                </button>
            </td>
        </tr>
        </tbody>
                    </table>
                </div>
            </div>
        )
    }
}
    Cart.propTypes = {
    addCartCount: PropTypes.func.isRequired,
    reduceCartCount: PropTypes.func.isRequired,
    fetchCarts: PropTypes.func.isRequired,
    cart: PropTypes.array.isRequired
    };

    const mapStateToProps = state => {
        return { cart: state.cart.cart };
    };
    const mapDispatchToProps = {
        fetchCarts,
        addCartCount,
        reduceCartCount
    };

export default connect(mapStateToProps, mapDispatchToProps)(Cart);

// vue-app/src/cart/cart.vue
<template>
  <div>
                <div class="container">
                    <table>
                        <tbody>
                        <tr>
                            <th>| Item(s)    |</th>
                            <th>| Quantity   |</th>
                            <th>| Unit Price |</th>
                            <th>| Total Prices     |</th>
                        </tr>
         <tr v-for="movie in rentalMovies" v-bind:key="movie.ProductId">
            <td><strong>{{movie.Title}}</strong></td>
            <td>{{movie.Quantity}}</td>
            <td>$ {{movie.TotalPrice/movie.Quantity}}</td>
            <td>$ {{movie.TotalPrice}}</td>
        </tr>
        <tr>    
            <td colSpan="2"></td>
            <td>
                 <strong>
                     SubTotal : 
                 </strong>
            </td>
                <td>
                  <strong>
                       $ {{subTotal}}
                  </strong>
                </td>
        </tr>
        <tr>    
            <td colSpan="2"></td>
            <td>
                <strong>
                    Tax Applicable :
                </strong>
            </td>
            <td>
                <strong>
                    $ {{taxable}}
                </strong>
            </td>
        </tr>
        <tr>    
            <td colSpan="2"></td>
            <td>
                <strong>
                    Total Billable Amount : 
                </strong>
            </td>
            <td>
                <strong>
                    $ {{grandTotal}}
                </strong>
            </td>
        </tr>
        <tr>
            <td colSpan="2">
                <button class="checkout">
                    checkout!<span class="glyphicon glyphicon-shopping-cart"></span>    
                </button>
            </td>
            <td colSpan="2">
                <button class="go-back">
                     Go Back
                </button>
            </td>
        </tr>
        </tbody>
                    </table>
                </div>
            </div>  
</template>

<script>
import { mapGetters, mapActions } from 'vuex';

export default {
    name: "Cart",
    methods: {  
        ...mapActions(["fetchCarts"]),
        calc: function() {
                    let subTotal1=0;
                    let taxable1 =0;
                    let grandTotal1 =0;
                    this.rentalMovies.forEach(function(obj) { 
                         subTotal1 +=  obj.TotalPrice;
                     })
                    taxable1 = subTotal1/10;
                    grandTotal1 = subTotal1+taxable1;
                    this.taxable = taxable1.toString().slice(0,4)
                    this.grandTotal = grandTotal1.toString().slice(0,5)
                    this.subTotal = subTotal1
        }
    },
    computed: mapGetters(['rentalMovies']),
    created() {  
        this.fetchCarts()
        this.calc()
   
    },
    beforeUpdate() {
        this.calc()
    },
    data: function() {
        return  {
            subTotal:0,
            taxable: 0,
            grandTotal: 0                    
        }
    }
}
</script>

<style scoped>
.flex-container {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  align-self: center;
  text-align:center;
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
  align-self: center;
}

table{
    margin-left: auto;
    margin-right: auto;
    text-align:center;
}
th{
    background-color: gray;
}
button{ 
    background-color: gray; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}

</style>
